#!/usr/bin/env python

from typing import Any, Literal, TypedDict
import pathlib
from venv import create
import sys
import json


class AnswersType(TypedDict):
    create_tests: bool
    project_license: Literal["MIT", "BSD", "GPLv3", "Apache Software License 2.0", "Not open source"]
    project_name: str
    project_slug: str


class Input(TypedDict):
    answers: AnswersType
    template_dir: str
    output_dir: str


def main():
    context: Input = json.load(sys.stdin)
    path = pathlib.Path()
    output_dir_path = path / context["output_dir"]
    template_dir_path = path / context["template_dir"]

    if context["answers"]["project_license"] != "Not open source":
        with open(template_dir_path / "licences" / context["answers"]["project_license"], "r") as f:
            licence_content = f.read()

        with open(output_dir_path / "LICENSE", "w") as f:
            f.write(licence_content)


    print("Creating virtual environment in", output_dir_path)
    create(output_dir_path / ".venv")
    print("Virtual environment created")

if __name__ == "__main__":
    main()
