#!/usr/bin/env python

from typing import Literal, TypedDict
import pathlib
from venv import create
import sys
import json


class Context(TypedDict):
    create_tests: bool
    project_license: Literal["MIT", "BSD", "GPLv3", "Apache Software License 2.0", "Not open source"]
    project_name: str
    project_slug: str


class Input(TypedDict):
    context: Context
    template_dir: str
    output_dir: str


def main():
    context: Input = json.load(sys.stdin)
    path = pathlib.Path()
    output_dir_path = path / context["output_dir"] / ".venv"
    template_dir_path = path / context["output_dir"] / ".venv"
    print("Creating virtual environment in", output_dir_path)
    create(output_dir_path)
    print("Virtual environment created")

if __name__ == "__main__":
    main()
