name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: baker
            asset_name: baker-linux-amd64
          - os: windows-latest
            artifact_name: baker.exe
            asset_name: baker-windows-amd64.exe
          - os: macos-latest
            artifact_name: baker
            asset_name: baker-macos-amd64

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        run: cargo build --verbose --release

      - name: Run tests
        run: cargo test --verbose
